apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-login-sm
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames: [default]
  selector:
    matchLabels:
      app: web-login
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
